name: project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - openpyxl
  - jupyter
  - jupyter_contrib_nbextensions
  - voila
  - scikit-learn
  - altair
  - vega_datasets
  - matplotlib
  - seaborn
  - statsmodels
  - numpy
  - IPython
  - joblib
  - pathlib
  - datetime
  - itertools
  - matplotlib-base  # Um Colormap zu unterstützen